<?php

$basepath = '../../..';
$title = 'Heste typer';
require "{$basepath}/app_core/object_loader.php";
require "{$basepath}/global_modules/header.php";
?>
<?php
if (!in_array('global_admin', $_SESSION['rights']) && !in_array('hestetegner_admin', $_SESSION['rights'])) {
	ob_end_clean();
	header('Location: /');
}

if (filter_input(INPUT_POST, 'save_race')) {
	$name = $link_new->real_escape_string(filter_input(INPUT_POST, 'name'));
	$max_height = $link_new->real_escape_string(filter_input(INPUT_POST, 'max_height'));
	$min_height = $link_new->real_escape_string(filter_input(INPUT_POST, 'min_height'));
	$description = $link_new->real_escape_string(filter_input(INPUT_POST, 'description'));
	//	echo $description;
	$sql = "INSERT INTO `horse_races` (`name`, `max_height`, `min_height`, `description`) VALUES ('{$name}', $max_height, $min_height, '{$description}')";
	if (filter_input(INPUT_POST, 'race_id')) {
		$id = (int) filter_input(INPUT_POST, 'race_id');
		$sql = "UPDATE `horse_races` SET `name` = '{$name}', `max_height` = {$max_height}, `min_height` = {$min_height}, `description` = '{$description}' WHERE `id` = {$id}";
	}
	$link_new->query($sql);

	/* Update race-cache */
	$races_for_file = $link_new->query("SELECT `id`, `name`, `max_height`, `min_height`, `description` FROM `horse_races`")->fetch_all();
	$file_content = '<?php' . PHP_EOL;
	$file_content .= '/* This file is auto generated by "/admin/hestetegner/admin_races.php" */' . PHP_EOL;
	$file_content .= '$cached_races = [];' . PHP_EOL;
	foreach ($races_for_file as $race) {
		$file_content .= '$cached_races["' . $race[0] . '"] = ["name" => "' . $race[1] . '","id" => ' . $race[0] . '];' . PHP_EOL;
	}
	file_put_contents("{$basepath}/files.net-hesten.dk/cache_data/list_of_races.php", $file_content);
	/* */
	header('Location: /admin/hestetegner/admin_races.php');
	exit();
}
?>
<script src="https://<?= filter_input(INPUT_SERVER, 'HTTP_HOST'); ?>/scripts/tinymce/tinymce.min.js"></script>
<script>
	tinymce.init({
		selector: 'textarea[name="description"]'
	});
</script>
<style>
	@font-face {
		font-family: 'tinymce';
		src: url('/admin/elements/fonts/tinymce.woff') format('woff2');
	}

	#race_add_form input {
		width: 150px;
		margin: 0;
	}

	#race_add_form input:first-child {
		width: 300px;
	}

	#race_add_form textarea {
		clear: both;
		display: block;
		width: 600px;
	}

	table {
		width: 100%;
	}

	td {
		border: 1px rgba(33, 33, 33, 0.5) solid;
		padding: 1em;
	}
</style>
<section>
	<header>
		<h2 class="raised">Tilføj Race</h2>
	</header>
	<form id="race_add_form" action="" method="post">
		<?php
		$race = false;
		if (isset($_GET['edit_race'])) {
			$race_id = (int) $_GET['edit_race'];
			$race = $link_new->query("SELECT `id`, `name`, `max_height`, `min_height`, `description` FROM `horse_races` WHERE `id` = {$race_id} LIMIT 1")->fetch_all();
		?>
			<input type="hidden" name="race_id" value="<?= $race_id; ?>" />
		<?php
		}
		?>
		<input required="required" type="text" name="name" placeholder="Racenavn" <?= ($race ? " value='{$race[0][1]}' " : ''); ?> />
		<input required="required" type="text" name="min_height" placeholder="Minimum højde i cm." <?= ($race ? " value='{$race[0][3]}' " : ''); ?> />
		<input required="required" type="text" name="max_height" placeholder="Max højde i cm." <?= ($race ? " value='{$race[0][2]}' " : ''); ?> />
		<textarea name="description" placeholder="Beskrivelse"><?= ($race ? $race[0][4] : ''); ?></textarea>
		<input type="submit" name="save_race" value="Gem" />
	</form>
</section>
<section>
	<header>
		<h2 class="raised">Racer</h2>
	</header>
	<table>
		<thead>
			<td>Navn</td>
			<td>Højde</td>
			<td>Beskrivelse</td>
			<td>Rediger</td>
		</thead>
		<?php
		$created_races = [];
		$races = $link_new->query("SELECT `id`, `name`, `max_height`, `min_height`, `description` FROM `horse_races`")->fetch_all();
		foreach ($races as $race) {
			$created_races[] = $race[1];
			//			continue;
		?>
			<tr>
				<td><?= $race[1]; ?></td>
				<td><?= $race[3]; ?> -> <?= $race[2]; ?></td>
				<td><?= $race[4]; ?></td>
				<td><a href="?edit_race=<?= $race[0]; ?>">Edit</a></td>
			</tr>
		<?php
		}
		?>
	</table>
	<br />
	<br />
</section>
<?php
require "{$basepath}/global_modules/footer.php";
